src/main/java/Storage/Storage.java, src/main/java/storage/Storage.java
=> Branch storage

src/main/java/commands/Command.java, src/main/java/parser/Parser.java
=> Create Parser class to parse commands

config/checkstyle/checkstyle.xml, src/main/java/exceptions/FitnessException.java, src/main/java/exceptions/FocusException.java, src/main/java/exceptions/HabitException.java, src/main/java/exceptions/ReflectException.java, src/main/java/exceptions/SleepException.java, src/main/java/exceptions/Wellness360Exception.java
=> Create Exceptions package

src/main/java/Main.java, src/main/java/commands/Command.java, src/main/java/commands/reflectcommands/GetReflectionQuestionsCommand.java, src/main/java/parser/Parser.java, src/main/java/parser/ReflectionCommandParser.java, src/main/java/parser/SleepCommandParser.java, src/main/java/reflection/Reflection.java, src/main/java/reflection/ReflectionManager.java, src/main/java/reflection/ReflectionQuestion.java, src/main/java/reflection/ReflectionQuestionBank.java, src/main/java/ui/Ui.java, src/test/java/reflect/ReflectQuestionBankTest.java
=> Branch reflection

src/main/java/Main.java, src/main/java/commands/habitcommands/AddHabitCommand.java, src/main/java/commands/habitcommands/ListHabitsCommand.java, src/main/java/commands/habitcommands/UpdateHabitCountCommand.java, src/main/java/exceptions/Wellness360Exception.java, src/main/java/habit/Habit.java, src/main/java/habit/HabitTracker.java, src/main/java/parser/HabitCommandParser.java, src/main/java/parser/Parser.java, src/main/java/ui/Ui.java
=> Branch habit v1.0

src/main/java/Main.java, src/main/java/commands/focuscommands/StartTimerCommand.java, src/main/java/commands/focuscommands/StopTimerCommand.java, src/main/java/exceptions/Wellness360Exception.java, src/main/java/focus/FocusTimer.java, src/main/java/parser/FocusCommandParser.java, src/main/java/parser/Parser.java, src/test/java/focus/FocusTimerTest.java
=> Add focus timer feature

src/main/java/commands/focuscommands/SwitchTimerCommand.java, src/main/java/focus/CountdownTimer.java, src/main/java/focus/CountupTimer.java, src/main/java/focus/FocusTimer.java, src/main/java/parser/FocusCommandParser.java
=> Add countdown timer for focus timer class

src/main/java/commands/habitcommands/DeleteHabitCommand.java, src/main/java/habit/HabitTracker.java, src/main/java/parser/HabitCommandParser.java
=> Add delete habit feature for habit tracker

.gitignore, src/main/java/habit/Habit.java, src/main/java/habit/HabitTracker.java, src/main/java/storage/habit/HabitTrackerStorage.java
=> Add save to local storage feature for habit tracker

src/main/java/commands/reflectcommands/ListFavouriteReflectionsCommand.java, src/main/java/commands/reflectcommands/ReflectionHelpCommand.java, src/main/java/commands/reflectcommands/UnsaveFromFavouritesCommand.java, src/main/java/parser/ReflectionCommandParser.java, src/main/java/reflection/FavoriteReflectionsList.java, src/main/java/reflection/ReflectionList.java, src/main/java/reflection/ReflectionManager.java, src/main/java/reflection/ReflectionQuestionBank.java, src/test/java/reflect/FavoriteReflectionsListTest.java, src/test/java/reflect/ReflectQuestionBankTest.java
=> Branch reflection v2.0

src/main/java/commands/focuscommands/SetPauseCommand.java, src/main/java/commands/focuscommands/SetResumeCommand.java, src/main/java/commands/focuscommands/StartTimerCommand.java, src/main/java/commands/focuscommands/StopTimerCommand.java, src/main/java/commands/focuscommands/SwitchTimerCommand.java, src/main/java/focus/CountdownTimer.java, src/main/java/focus/CountupTimer.java, src/main/java/focus/FocusTimer.java, src/main/java/parser/FocusCommandParser.java, src/test/java/focus/FocusTimerTest.java
=> Add pause and resume feature for focus timer

docs/UserGuide.md
Update table of contents regarding reflection feature
=> Update user guide for reflection feature

docs/DeveloperGuide.md
Propose to use shared base format for developer guide
=> Update developer guide base format

src/main/java/commands/focuscommands/CheckTimeCommand.java, src/main/java/commands/focuscommands/SetTimingCommand.java, src/main/java/focus/CountdownTimer.java, src/main/java/focus/CountupTimer.java, src/main/java/focus/FocusTimer.java, src/main/java/parser/FocusCommandParser.java
=> Add set timer and check time feature for focus timer

src/main/java/commands/habitcommands/SetPriorityCommand.java, src/main/java/commands/habitcommands/SortHabitsCommand.java, src/main/java/commands/habitcommands/UpdateHabitCountCommand.java, src/main/java/habit/Habit.java, src/main/java/habit/HabitTracker.java, src/main/java/habit/Priority.java, src/main/java/parser/HabitCommandParser.java, src/main/java/storage/habit/HabitTrackerStorage.java, src/test/java/habit/HabitTrackerTest.java
=> Add priority levels for habits

src/main/java/commands/fitnesscommands/DeleteExerciseCommand.java, src/main/java/commands/fitnesscommands/ErrorMessageConstants.java, src/main/java/fitness/FitnessMotivator.java, src/main/java/fitness/UiMessageConstants.java, src/main/java/parser/FitnessCommandParser.java, src/main/java/parser/Parser.java
Made fitness commands non-case-sensitive
=> Minor changes to FitnessMotivator Feature

docs/DeveloperGuide.md, docs/UserGuide.md
Made minor changes to developer guide as well
=> Minor changes to User Guide

src/main/java/commands/habitcommands/SetPriorityCommand.java
Refactor set priority command class to abstract complex conditions as pointed out by @StanleyW00 in #120
=> Refactor set priority command class 

docs/UserGuide.md
=> Update User guide for focus timer

docs/DeveloperGuide.md, src/main/java/commands/focuscommands/SetResumeCommand.java, src/main/java/commands/focuscommands/SetTimingCommand.java, src/main/java/commands/focuscommands/StopTimerCommand.java, src/main/java/commands/focuscommands/SwitchTimerCommand.java
=> Bug fixes and update developer guide for focus feature 
